server:
  port: 0

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:customerdb5
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


  liquibase:
    change-log: classpath:config/liquibase/master.xml

  application:
    name: customer-service
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
      config:
        watch:
          enabled: false
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URI:localhost:9092}
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bindings:
        output:
          destination: order_notification
          contentType: application/json

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ "configprops", "env", "health", "info", "threaddump", "logfile", "prometheus" ]